---
title: "YOU GIVE ME THE CONTENT, I CREATE THE BOOK"
author: "_Baran Dogru_"
date: ''
site: bookdown::bookdown_site
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
I can create online books for you to use in your class, work or anywhere you wish. Only thing you need to do is to provide the content!  

<mark>I strongly suggest you to visit the two books I have written before. They can be found in [Example Books] section.</mark>

## Basic Properties

* HTML files to freely and easily host the website on GitHub or your preferred service
* PDF and EPUB download options
* Modifying text size, text font and background theme in real time
* Search button that can trace the whole document
* Collapsable table of contents
* Images in anywhere you want

## Advanced Properties

* Addition of front page and logo 
* Addition of mathematical equations with LaTeX

## More Advanced Properties

* Addition of custom css styling
* Creation of non-English books
* Analyzing your data on R, providing insights and stylish plotting

## Example Books
Both of these books were written in Turkish but are nice examples. (Custom styles were not wanted.)

* [My First Book][book1]
* [My Second Book][book2]

[book1]: https://acikenerji.github.io/verianalizi101/index.html 
[book2]: https://acikenerji.github.io/R-shiny/index.html 
